<a href="https://colab.research.google.com/github/Saumya0330/Saumya-USC420/blob/main/cog_assignment3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
df=pd.read_csv('/content/assignment3 - Sheet1.csv')

In [ ]:
df.head(10)

   Tid Refund Marital status Taxable income Cheat
0    1    yes         Single           125K    No
1    2     no        Married           100K    No
2    3     no         Single            70K    No
3    4    yes        Married           120K    No
4    5     no       Divorced            95K   Yes
5    6     no        Married            60K    No
6    7    yes       Divorced           220K    No
7    8     no         Single            85K   Yes
8    9     no        Married            75K    No
9   10     no         Single            90K   Yes

Q.2 From the above table that you have created, locate row 0, 4, 7 and 8 using DataFrame.

In [ ]:
print(df.loc[[0,4,7,8]])

   Tid Refund Marital status Taxable income Cheat
0    1    yes         Single           125K    No
4    5     no       Divorced            95K   Yes
7    8     no         Single            85K   Yes
8    9     no        Married            75K    No

Q.3 Navigate the DataFrame and do the following task for the table created in question 1:
1. Select row from index 3 to 7.
2. Select row from index 4 to 8, and column 2 to 4.
3. Select all rows with column index 1 to 3 (include index 3 during selection).

In [ ]:
print(df.loc[2:6])
print(df.iloc[3:8,1:4])
print(df.loc[:,['Tid','Marital status','Taxable income']])

   Tid Refund Marital status Taxable income Cheat
2    3     no         Single            70K    No
3    4    yes        Married           120K    No
4    5     no       Divorced            95K   Yes
5    6     no        Married            60K    No
6    7    yes       Divorced           220K    No
  Refund Marital status Taxable income
3    yes        Married           120K
4     no       Divorced            95K
5     no        Married            60K
6    yes       Divorced           220K
7     no         Single            85K
   Tid Marital status Taxable income
0    1         Single           125K
1    2        Married           100K
2    3         Single            70K
3    4        Married           120K
4    5       Divorced            95K
5    6        Married            60K
6    7       Divorced           220K
7    8         Single            85K
8    9        Married            75K
9   10         Single            90K

Q.4 Read a csv file and display its first five rows.

In [ ]:
df1=pd.read_csv('/content/earthquakes.csv')
df1.head()

,year,month,day,richter,area,region,deaths
0,1902,April,19,7.5,Quezaltenango and San Marco,Guatemala,2000.0
1,1902,December,16,6.4,Uzbekistan,Russia,4700.0
2,1903,April,28,7.0,Malazgirt,Turkey,3500.0
3,1903,May,28,5.8,Gole,Turkey,1000.0
4,1905,April,4,7.5,Kangra,India,19000.0

Q.5 From the csv file (uploaded in the Q.4) delete row 4, and delete column 3. Display the
result.

In [ ]:
df1.drop(df1.columns[2],axis=1,inplace=True)
df1.drop(df1.index[3],axis=0,inplace=False)

,year,month,richter,area,region,deaths
0,1902,April,7.5,Quezaltenango and San Marco,Guatemala,2000.0
1,1902,December,6.4,Uzbekistan,Russia,4700.0
2,1903,April,7.0,Malazgirt,Turkey,3500.0
4,1905,April,7.5,Kangra,India,19000.0
5,1906,January,8.8,Esmeraldas (off coast),Ecuador,1000.0
...,...,...,...,...,...,...
118,1998,May,6.6,Border,Afghanistan-Tajikistan,4000.0
119,1998,July,7.0,Papua,New Guinea,2183.0
120,1999,January,6.1,Armenia,Colombia,1185.0
121,1999,August,7.6,Izmit,Turkey,17118.0
122,1999,September,7.6,Taichung,Taiwan,2400.0

Q.6 Create a sample dataset (employees.csv) containing information about employees in
a company.

In [ ]:
import pandas as pd
df2=pd.read_csv('/content/Employees - Sheet1.csv')
df2

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5

WAP to determine the following using dataset in Q6:
a) Shape (number of rows and columns) of the DataFrame.
b) Summary of the DataFrame that includes the data types and non-null counts for
each column.
c) Generate descriptive statistics.
d) Display the first 5 rows and last 3 rows of the dataset.

In [ ]:
print('no of rows: ',len(df2.axes[0]))
print('no of cols: ',len(df2.axes[1]))

no of rows:  5
no of cols:  10

In [ ]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, 1 to 0
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Employee_ID          5 non-null      int64
 1   Name                 5 non-null      object
 2   Department           5 non-null      object
 3   Age                  5 non-null      int64
 4   Salary               5 non-null      int64
 5   Years_of_Experience  5 non-null      int64
 6   Joining_Date         5 non-null      object
 7   Gender               5 non-null      object
 8   Bonus                5 non-null      int64
 9   Rating               5 non-null      float64
dtypes: float64(1), int64(5), object(4)
memory usage: 612.0+ bytes

In [ ]:
df2.describe()
df2.describe(include='all')

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
count,5.000000,5,5,5.000000,5.00000,5.000000,5,5,5.0,5.000000
unique,NaN,5,4,NaN,NaN,NaN,5,2,NaN,NaN
top,NaN,Alice,IT,NaN,NaN,NaN,2020-03-15,Male,NaN,NaN
freq,NaN,1,2,NaN,NaN,NaN,1,3,NaN,NaN
mean,103.000000,NaN,NaN,34.000000,60000.00000,7.400000,NaN,NaN,5500.0,4.100000
std,1.581139,NaN,NaN,5.612486,7905.69415,3.847077,NaN,NaN,1000.0,0.494975
min,101.000000,NaN,NaN,28.000000,50000.00000,3.000000,NaN,NaN,4500.0,3.500000
25%,102.000000,NaN,NaN,29.000000,55000.00000,4.000000,NaN,NaN,5000.0,3.800000
50%,103.000000,NaN,NaN,34.000000,60000.00000,8.000000,NaN,NaN,5000.0,4.000000
75%,104.000000,NaN,NaN,38.000000,65000.00000,10.000000,NaN,NaN,6000.0,4.500000
max,105.000000,NaN,NaN,41.000000,70000.00000,12.000000,NaN,NaN,7000.0,4.700000

In [ ]:
df2.head()

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5

In [ ]:
df2.tail(3)

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5

e) Calculate the following statistics from the dataset:
i. The average salary of employees.
ii. The total bonus paid to all employees.
iii. The youngest employee's age.
iv. The highest performance rating.

In [ ]:
print('average salary: ',df2['Salary'].mean())
print('total bonus: ',df2['Bonus'].sum())
print('youngest employee age: ',df2['Age'].min())
print('highest performance rate: ',df2['Rating'].max())

average salary:  60000.0
total bonus:  27500
youngest employee age:  28
highest performance rate:  4.7

f) Sort the DataFrame by the Salary column in descending order.

In [ ]:
df2.sort_values(by='Salary',ascending=False)

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5

g) Add a new column that categorizes employees based on their performance rating:

i. Excellent for ratings >= 4.5
ii. Good for ratings >= 4.0 but < 4.5
iii. Average for ratings < 4.0

In [ ]:
df2['Feedback'] = ['Excellent' if x >= 4.5 else 'Good' if x >= 4 and x < 4.5 else 'Average' for x in df2['Rating']]
df2

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Feedback
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5,Average
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7,Excellent
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5,Excellent

h) Identify missing values in the DataFrame.

In [ ]:
df2.isnull()

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Feedback
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
0,False,False,False,False,False,False,False,False,False,False,False

i) Rename the Employee_ID column to ID.

In [ ]:
df2.rename(columns={'Employee_ID':'ID'})

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Feedback
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5,Average
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7,Excellent
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5,Excellent

j) Find all employees who:

i. Have more than 5 years of experience.
ii. Belong to the IT department.

In [ ]:
df2[(df2['Years_of_Experience']>5 ) & (df2['Department']=='IT')]

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Feedback
1,102,Bob,IT,34,70000,8.0,2017-07-19,Male,7000,4.0,Good
2,103,Charlie,IT,41,65000,10.0,2013-06-01,Male,6000,3.8,Average

k) Modify the dataset by adding a new column, Tax, which deducts 10% of the
Salary.

In [ ]:
df2['Salary_after_Tax']=[x-0.1*x for x in df2['Salary']]
df2

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Feedback,Salary_after_Tax
1,102,Bob,IT,34,70000,8.0,2017-07-19,Male,7000,4.0,Good,63000.0
2,103,Charlie,IT,41,65000,10.0,2013-06-01,Male,6000,3.8,Average,58500.0
4,105,Edward,Sales,38,60000,12.0,2010-11-25,Male,5000,3.5,Average,54000.0
3,104,Diana,Marketing,28,55000,NaN,2021-02-10,Female,4500,4.7,Excellent,49500.0
0,101,Alice,HR,29,50000,NaN,2020-03-15,Female,5000,4.5,Excellent,45000.0

l) Save the modified DataFrame (with added columns) to a new CSV file.

In [ ]:
df2.to_csv('modified_employees.csv',index=False)
df3=pd.read_csv('modified_employees.csv')
df3

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Feedback,Salary_after_Tax
0,102,Bob,IT,34,70000,8.0,2017-07-19,Male,7000,4.0,Good,63000.0
1,103,Charlie,IT,41,65000,10.0,2013-06-01,Male,6000,3.8,Average,58500.0
2,105,Edward,Sales,38,60000,12.0,2010-11-25,Male,5000,3.5,Average,54000.0
3,104,Diana,Marketing,28,55000,NaN,2021-02-10,Female,4500,4.7,Excellent,49500.0
4,101,Alice,HR,29,50000,NaN,2020-03-15,Female,5000,4.5,Excellent,45000.0